# Generated by Django 5.1.2 on 2024-11-21 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sessions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CenaInterativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("configuracao", models.JSONField()),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("reputation", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        default="images/default.jpg", upload_to="images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HackingMiniGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("configuracao", models.JSONField()),
                ("descricao", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            (
                                "invasion",
                                "Hacking para invadir o sistema da célula cibernética",
                            ),
                            (
                                "pattern",
                                "Jogador resolve um puzzle para identificar padrões ocultos",
                            ),
                            (
                                "stealth",
                                "Hacking para acessar o servidor central sem ser detectado",
                            ),
                            (
                                "complex",
                                "Hacking complexo com várias etapas, refletindo a escolha do jogador",
                            ),
                        ],
                        default="pattern",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Missao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("furtividade", "Furtividade"),
                            ("combate", "Combate"),
                        ],
                        max_length=50,
                    ),
                ),
                ("parametros", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="VariavelNarrativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("valor", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("num", models.IntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="game.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Screen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("num", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("custom_css", models.TextField(blank=True, null=True)),
                ("custom_js", models.TextField(blank=True, null=True)),
                ("opcoes", models.JSONField(blank=True, null=True)),
                ("mensagens_interativas", models.TextField(blank=True, null=True)),
                ("flashback", models.BooleanField(default=False)),
                ("condicoes", models.JSONField(blank=True, null=True)),
                (
                    "cenas_interativas",
                    models.ManyToManyField(blank=True, to="game.cenainterativa"),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screens",
                        to="game.chapter",
                    ),
                ),
                (
                    "hacking_mini_games",
                    models.ManyToManyField(blank=True, to="game.hackingminigame"),
                ),
                ("missoes", models.ManyToManyField(blank=True, to="game.missao")),
                (
                    "personagens",
                    models.ManyToManyField(blank=True, to="game.character"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                (
                    "hacking_mini_game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="choices",
                        to="game.hackingminigame",
                    ),
                ),
                (
                    "next_screen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_choices",
                        to="game.screen",
                    ),
                ),
                (
                    "screen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="game.screen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_screen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.screen",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessions.session",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
