# Generated by Django 5.1.2 on 2024-11-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="variaveis_narrativas",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
