# Generated by Django 5.1.2 on 2024-11-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_character_image_character_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='character_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
