# Generated by Django 5.1.2 on 2024-11-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_screen_cenas_interativas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='cenas_interativas',
            field=models.ManyToManyField(blank=True, related_name='linked_screens', to='game.cenainterativa'),
        ),
        migrations.AlterField(
            model_name='cenainterativa',
            name='escolhas',
            field=models.ManyToManyField(blank=True, related_name='cenas_interativas', to='game.choice'),
        ),
        migrations.AlterField(
            model_name='cenainterativa',
            name='screens',
            field=models.ManyToManyField(blank=True, related_name='cenas_interativas_instances', to='game.screen'),
        ),
    ]
