# Generated by Django 5.1.2 on 2024-11-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_remove_chapter_character_image_chapter_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="num",
            field=models.IntegerField(default=0),
        ),
    ]
