# Generated by Django 5.1.2 on 2024-11-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_screen_cenas_interativas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='alinhamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
