# Generated by Django 5.1.2 on 2024-11-21 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_screen_alinhamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackingminigame',
            name='next_screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_mini_games', to='game.screen'),
        ),
    ]
