# Generated by Django 5.1.2 on 2024-11-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_hackingminigame_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='hacking_mini_games',
        ),
    ]
