# Generated by Django 5.1.2 on 2024-11-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_screen_hacking_mini_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(default='images/zero.png', upload_to='images/'),
        ),
    ]
