# Generated by Django 5.1.2 on 2024-11-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_screen_choice_next_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='custom_css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='custom_js',
            field=models.TextField(blank=True, null=True),
        ),
    ]
