# Generated by Django 5.1.2 on 2024-11-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackingminigame',
            name='dificuldade',
            field=models.CharField(default='média', max_length=50),
        ),
        migrations.AddField(
            model_name='hackingminigame',
            name='tempo_limite',
            field=models.IntegerField(default=30),
        ),
    ]
