# Generated by Django 5.1.2 on 2024-11-19 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_screen_custom_css_screen_custom_js'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game.screen'),
        ),
        migrations.AddField(
            model_name='screen',
            name='chapter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='game.chapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game.chapter'),
        ),
    ]
