# Generated by Django 5.1.2 on 2024-11-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_hackingminigame_dificuldade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackingminigame',
            name='tipo',
            field=models.CharField(choices=[('invasion', 'Hacking para invadir o sistema da célula cibernética'), ('pattern', 'Jogador resolve um puzzle para identificar padrões ocultos'), ('stealth', 'Hacking para acessar o servidor central sem ser detectado'), ('complex', 'Hacking complexo com várias etapas, refletindo a escolha do jogador'), ('clicker', 'Hacking clicker, onde o jogador enfrenta a máquina para ver quem clica mais')], default='complex', max_length=50),
        ),
    ]
