# Generated by Django 5.1.2 on 2024-11-19 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_screen_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='game.chapter'),
        ),
    ]
