# Generated by Django 5.1.2 on 2024-11-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_hackingminigame_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='current_screen',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='session',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
