# Generated by Django 5.1.2 on 2024-11-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_screen_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
