# Generated by Django 5.1.2 on 2024-11-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_screen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='num',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
