# Generated by Django 5.1.2 on 2024-11-19 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_screen_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='content',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='next_chapter',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='next_chapter',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='current_chapter',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.screen'),
        ),
    ]
