# Generated by Django 5.1.2 on 2024-11-20 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0015_remove_chapter_content_remove_chapter_next_chapter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="personagens",
            field=models.ManyToManyField(blank=True, to="game.character"),
        ),
        migrations.AlterField(
            model_name="screen",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="screens",
                to="game.chapter",
            ),
        ),
        migrations.AlterField(
            model_name="screen",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screen",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="screen",
            name="num",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screen",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
