# Generated by Django 5.1.2 on 2024-11-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0015_remove_chapter_content_remove_chapter_next_chapter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CenaInterativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("configuracao", models.JSONField()),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="HackingMiniGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("configuracao", models.JSONField()),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Missao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("furtividade", "Furtividade"),
                            ("combate", "Combate"),
                        ],
                        max_length=50,
                    ),
                ),
                ("parametros", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="VariavelNarrativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("valor", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="screen",
            name="condicoes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="flashback",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="screen",
            name="mensagens_interativas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="opcoes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="personagens",
            field=models.ManyToManyField(blank=True, to="game.character"),
        ),
        migrations.AddField(
            model_name="screen",
            name="cenas_interativas",
            field=models.ManyToManyField(blank=True, to="game.cenainterativa"),
        ),
        migrations.AddField(
            model_name="screen",
            name="hacking_mini_games",
            field=models.ManyToManyField(blank=True, to="game.hackingminigame"),
        ),
        migrations.AddField(
            model_name="screen",
            name="missoes",
            field=models.ManyToManyField(blank=True, to="game.missao"),
        ),
    ]
