# Generated by Django 5.1.2 on 2024-11-21 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0016_screen_personagens_alter_screen_chapter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CenaInterativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("configuracao", models.JSONField()),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="HackingMiniGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("configuracao", models.JSONField()),
                ("descricao", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            (
                                "invasion",
                                "Hacking para invadir o sistema da célula cibernética",
                            ),
                            (
                                "pattern",
                                "Jogador resolve um puzzle para identificar padrões ocultos",
                            ),
                            (
                                "stealth",
                                "Hacking para acessar o servidor central sem ser detectado",
                            ),
                            (
                                "complex",
                                "Hacking complexo com várias etapas, refletindo a escolha do jogador",
                            ),
                        ],
                        default="pattern",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Missao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("furtividade", "Furtividade"),
                            ("combate", "Combate"),
                        ],
                        max_length=50,
                    ),
                ),
                ("parametros", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="VariavelNarrativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("valor", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="screen",
            name="condicoes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="flashback",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="screen",
            name="mensagens_interativas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="opcoes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="character",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="game.character",
            ),
        ),
        migrations.AlterField(
            model_name="screen",
            name="chapter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screens",
                to="game.chapter",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screen",
            name="cenas_interativas",
            field=models.ManyToManyField(blank=True, to="game.cenainterativa"),
        ),
        migrations.AddField(
            model_name="choice",
            name="hacking_mini_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="choices",
                to="game.hackingminigame",
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="hacking_mini_games",
            field=models.ManyToManyField(blank=True, to="game.hackingminigame"),
        ),
        migrations.AddField(
            model_name="screen",
            name="missoes",
            field=models.ManyToManyField(blank=True, to="game.missao"),
        ),
    ]
