# Generated by Django 5.1.2 on 2024-11-20 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0016_cenainterativa_hackingminigame_missao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="hacking_mini_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="choices",
                to="game.hackingminigame",
            ),
        ),
    ]
