# Generated by Django 5.1.2 on 2024-11-29 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_hackingminigame_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='trilha_sonora',
            field=models.FileField(blank=True, null=True, upload_to='trilhas_sonoras/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='num',
            field=models.IntegerField(),
        ),
    ]
